### PR TITLE
Test all combinations

### LINKED ISSUE #36: Test phyloreference logical expressions by trying every possible combination
The code for generating phyloreference OWL expressions is pretty complicated. One way to make sure we're generating every possible expression is:
1. Generate phyloreferences for every possible topology for three specifiers.
2. Make sure that we can resolve an MRCA of all specifiers on every possible topology.
3. Generate phyloreferences with every specifier as an internal specifier except for one, which is treated as an external specifier. When the external specifier's parent is the root node, it should be sibling to the resolved node; in every other case, the phyloreference should fail to resolve.

We could extend this test to four and five specifiers, and we should try to come with a way of testing multiple external specifiers.

### PR DESCRIPTION
**Pull request by gaurav**
This PR includes a Javascript script for generating every possible bifurcating and multifurcating tree for a given number of leaf nodes (A, B, C, D, ...), and for recording these in Phyx files with expectations on where two simple phyloreferences are expected to resolve: the MRCA of A and B, and the phyloref that includes A but excludes C. It also includes a set of Bash scripts for generating trees for n=2, 3, 4, 5 and 6 leaf nodes and for testing all of them with JPhyloRef to ensure that they resolve as expected. I used a Python script (which uses DendroPy) to verify that all generated trees for a particular run are unique, indicating that we have generated every possible topography for each run.

Closes #36.

### CODE REVIEW

**Review by hlapp — APPROVED** [review]
Looks more or less good to me. Two comments:
- There seem to be log files as part of the PR (and thus repo) which are big. Can you confirm that this is necessary?
- You wrote your own version of `is_bifurcating()`. Doesn't Dendropy have that already?

**Comment by gaurav** [comment]
Thanks, Hilmar!

> There seem to be log files as part of the PR (and thus repo) which are big. Can you confirm that this is necessary?
I like the idea of leaving `log-for-generate-tests.txt` in the repo since it includes the full Newick strings we use to test resolution (the `Nab_cdn` node labeling syntax I describe in the manuscript). Alternatively, I could write those into the Nexus files: I wrote the trees there before I added those node labeling, since otherwise I'd have to remove the internal node labels in DendroPy before comparing them. Which do you think is the better approach?

> You wrote your own version of `is_bifurcating()`. Doesn't Dendropy have that already?
I couldn't find one in the DendroPy docs. I'll dig into it a bit more today and see if I can find something.

**Comment by hlapp** [comment]
> I like the idea of leaving `log-for-generate-tests.txt` in the repo since it includes the full Newick strings we use to test resolution (the `Nab_cdn` node labeling syntax I describe in the manuscript). Alternatively, I could write those into the Nexus files: I wrote the trees there before I added those node labeling, since otherwise I'd have to remove the internal node labels in DendroPy before comparing them. Which do you think is the better approach?

I don't know. If the trees (Newick strings) make the bulk of the size of the file then this will be equally the case with a NEXUS file, and hence no space savings. On the other hand, if you are using the log file as a file of trees, then NEXUS would be the more appropriate format, wouldn't it? I'll leave final judgement to you.

> 
> > You wrote your own version of `is_bifurcating()`. Doesn't Dendropy have that already?
> 
> I couldn't find one in the DendroPy docs. I'll dig into it a bit more today and see if I can find something.

Funny. You might consider contributing a pull request to Dendropy if it's really not there.

**Comment by gaurav** [comment]
Okay, I've:
- Removed the log files.
- Added debugging information previously captured in the log files in the Nexus file being generated (see the n=4 run as an example: https://github.com/phyloref/phyx.js/blob/56c96d59bdaaaf9559d66f51804c51c223550ce7/every-topology-testing/n4/trees.nex)
- Added a check to validate-trees.py to make sure that all the trees in each Nexus file have the same number of leaf nodes.
- Updated CHANGELOG.

Jeet agrees that it would be a good idea to move `is_bifurcating()` (as well as my generate-all-multifurcating-trees algorithm
) to DendroPy, so I might try to do that once we have the Phyx.js manuscript done.

@hlapp Could you please have another look at this PR and let me know if you think it's good to go?

**Review by hlapp — APPROVED** [review]
LGTM!

**Pull request merged**
